services:
  vet-postgres:
    image: postgres
    container_name: vet-postgres
    restart: always
    shm_size: 128mb
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - './volumes/postgresql:/var/lib/postgresql/data'
      - './init-sql:/docker-entrypoint-initdb.d'
